### ISSUE TITLE
differs by more than two lines at "make link"

### ISSUE THREAD

**Issue by XingchengLin** [lequieu/1cpn-model#2]
Hi,

There is one error at step 5 in "Quick start guide", when trying to patch the 1CPN codes into the stable_16Mar2018 version

5. Link 1CPN with LAMMPS.
cd $D_1CPN/1cpn-model/src/lammps
make link

The error is related to the file atom.cpp, showing: 
differs by more than two lines.
make: *** [link] Error 1

Is there any solution for that?

Thanks,

**Comment by kthackst** [comment]
Howdy,

I have also had the same issue, though I have an additional line in my error:
```
/home/user/1cpn/1cpn-model/src/lammps/atom.cpp differs by more than two lines.
Makefile:54: recipe for target 'link' failed
make: *** [link] Error 1
```
Probably related, when I go to run the simulation later, I get the following error:
```
~/1cpn/example$ ${D_1CPN}/lammps-1cpn/src/lmp_serial -i in.1cpn
LAMMPS (7 Aug 2019)
Reading data file ...
  orthogonal box = (-524.355 -524.355 -524.355) to (538.872 538.872 538.872)
  1 by 1 by 1 MPI processor grid
  reading atoms ...
  452 atoms
  452 ellipsoids
  scanning bonds ...
  3 = max bonds/atom
  scanning angles ...
ERROR on proc 0: Invalid atom ID in Angles section of data file (../atom.cpp:1147)
Last command: read_data in.lammps
```

**Comment by lequieu** [comment]
Hello! Thanks for bringing this to our attention. I've pushed a new commit that should fix this issue. LAMMPS linked and compiled OK for me, but I didn't run any examples. Let me know if it works for you. If so, I'll close this issue.

**Comment by kthackst** [comment]
Thanks, this did fix the link error! Unfortunately I still get the same error as posted above when I run the example involving the invalid atom ID.

**Comment by lequieu** [comment]
I ran a test simulation and everything worked okay with this new fix. Could you make sure that you're using a fresh copy of LAMMPS and try again? I'm not getting the error that you reported above. 

It does look like you're using LAMMPS (7 Aug 2019). Perhaps this could be your issue?

**Comment by XingchengLin** [comment]
I did some tests and can repeat Kyle's error. I think this line in atom.cpp is still necessary:
//        (atom1 == atom2) || (atom1 == atom3) || (atom2 == atom3)) //THIS LINE IS THE ONLY LINE CHANGED IN 1CPN
The updated repository deleted atom.cpp, causing the error

**Comment by lequieu** [comment]
Okay, I think I found the issue. This should be fixed in my most recent commit. 

Its turns out LAMMPS has changed how it handles its branches/tags (see https://lammps.sandia.gov/doc/Install_git.html) so that checking out `stable_16Mar2018 ` uses the command `git checkout stable_16Mar2018` instead of `git checkout -b stable_16Mar2018` (i.e. the `-b` flag should no longer be used. In fact the `-b` flag now just creates a new branch from master. As it turns out, the current master's version of `atom.cpp` doesn't need to be modified during the linking of 1CPN at all (and hence my confusion above). However since "stable_16Mar2018" is the version of LAMMPS that we've tested with 1CPN we'll have to keep updating `atom.cpp` during the linking step. 

Anyways please try the new commit and see if this works for you.

**Comment by kthackst** [comment]
I started over the install instructions with the different LAMMPS checkout command and of course your recent edits, and my error is gone, the simulation is running. Thanks!

**Comment by lequieu** [comment]
Great! Glad things are working!
